### ISSUE TITLE
PyPI version of VTK does not appear to provide vtkGraphLayout

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/LB-analysis-framework#166]
This causes the following problem:
```
python MoveCountsViewer.py -p 8 -f ../../data/stats/lb_iter -s out
[MoveCountsViewer] ### Started with Python 3.8.7
[MoveCountsViewer] Parsing command line arguments
Traceback (most recent call last):
  File "MoveCountsViewer.py", line 429, in <module>
    params.computeMoveCountsViewer()
  File "MoveCountsViewer.py", line 244, in computeMoveCountsViewer
    layout_vertices = vtk.vtkGraphLayout()
AttributeError: module 'vtkmodules.all' has no attribute 'vtkGraphLayout'
```

This is because PyPI (pip)'s version of VTK does not appear to provide `vtkGraphLayout.so` in `/usr/local/lib/python3.8/site-packages/vtkmodules/`

It should be investigated whether a custom build of VTK, turning ON the appropriate `Infovis` modules in CMake settings,resolves the issue.

**Comment by marcinwrobel1986** [comment]
Hello,
so the main key for this to work again was to install latest pypi VTK package.
Anyway I find the output file confusing. Attached below:
![move_counts](https://user-images.githubusercontent.com/47597569/153577992-eb08792d-e984-4e9e-b94e-5420c0c2598b.png)

Much better impression makes the OpenGL window generated when `interactive` is set to `True`. Attached below:
![Zrzut ekranu z 2022-02-11 10-20-10](https://user-images.githubusercontent.com/47597569/153578677-ea375cb5-4e4c-4d41-ae43-f51f45618cd9.png)

I need to take a look, what is wrong, becasue my latest push has not passed CI, but works fine on my machine.

**Comment by marcinwrobel1986** [comment]
Small update, back to the drawing board, because I have VTK from Paraview in the path and that is the reason it worked well :)

**Comment by marcinwrobel1986** [comment]
But there are bright sides as well, mainly I have found out that they changed API and LBAF is working with VTK 9.0.1, but not working with 9.0.2, 9.0.3 and the newest 9.1.0, so goot to know, but worse, that it's not working.
@ppebay Maybe an issue for that?

### TODO:
- check what was changed
- make LBAF works with the latest version

**Comment by marcinwrobel1986** [comment]
Some more interesting info => `MoveCountsViewer` works for me just fine.
@ppebay Please try to use it. Please make sure that there is nothing you don't want in you `PYTHONPATH` env var

**Comment by ppebay** [comment]
Thanks @marcinwrobel1986 for looking into this. I confirm it's **not** working for me, but as mentioned in the description, it also **cannot** work because the necessary shared object (`vtkGraphLayout.so`) is **not* provided by the version of VTK 9.0 that comes with PyPI.  [N..B.: in my case `PYTHONPATH` cannot play a role either because `vtkGraphLayout.so` is nowhere on the system].

The fundamental question is then: if it's working on your system, where is `vtkGraphLayout.so` found?

**Comment by marcinwrobel1986** [comment]
@ppebay I asked my friend, who works on Mac, to check that one for me. He is doing JS daily, so I gave him the instructions:
- clone the project
- check out branch `166-VTK-does-not-appear-to-provide-vtkGraphLayout`
- set virtualenv (to be 100% it is isolated)
- activate `venv` and install packages with `pip install -r requirements.txt`
- run `python src/Applications/MoveCountsViewer.py`

As you can see below he didn't have any problems. What is interesting is a fact, that's on my `Ubuntu` distro the output file looks strange, be he got really decent one. Thank you @mvciekzvbek
Printscreen he sent me is below:

<img width="1791" alt="Screenshot 2022-02-14 at 09 59 34" src="https://user-images.githubusercontent.com/47597569/153843375-4a88a991-4986-40f0-9bce-38fc01299036.png">
